version: '3'

services:
  caddy:
    container_name: caddy
    image: lucaslorentz/caddy-docker-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    command: -email your@email.here -agree=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy:/root/.caddy
    network_mode: "bridge"

volumes:
  caddy:
