version: '3.3'

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "certs:/letsencrypt"
        - "./traefik.toml:/traefik.toml"
    restart: unless-stopped
    network_mode: "bridge"
volumes:
  certs:
