[log]
  level = "ERROR"

[providers.docker]
  exposedByDefault = false

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"

[certificateResolvers]
  [certificatesResolvers.default.acme]
    email = "josh@joshjacobs.net"
    storage = "/letsencrypt/acme.json"
    [certificatesResolvers.default.acme.tlsChallenge]
