version: '3'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    restart: unless-stopped
    ports:
    - "8080:8080"
    - "5000:5000"
    - "25:25"
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home: