version: '3'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    restart: unless-stopped
    labels:
      - caddy.address=your.domain.here
      - caddy.targetport=8080
      - caddy.proxy.transparent=
    volumes:
      - jenkins_home:/var/jenkins_home
    network_mode: "bridge"

volumes:
  jenkins_home:
