version: '3'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    restart: unless-stopped
    environment:
    - VIRTUAL_HOST=jenkins.init.tools
    - VIRTUAL_PORT=8080
    - LETSENCRYPT_HOST=jenkins.init.tools
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped
    network_mode: "bridge"

volumes:
  jenkins_home:
