version: '3'

services:
  proxy:
    container_name: proxy
    build: ./proxy
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    environment:
        DEFAULT_HOST: proxy.local
    volumes:
      - certs:/etc/nginx/certs:ro
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  letsencrypt-companion:
    container_name: letsencrypt
    build: ./letsencrypt
    restart: unless-stopped
    environment:
      DEFAULT_EMAIL: # Your email for certificate notification
    volumes:
      - certs:/etc/nginx/certs
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - proxy

volumes:
  certs:
  conf.d:
  vhost.d:
  html:
